docker-compose-yaml: docker-compose.yml

project: wordpress-example

tasks:
  post-rollout:
    - run:
        name: install wordpress if not installed
        command: |
          if ! $(cd web && wp core is-installed); then
            cd web && wp core install --url=$LAGOON_ROUTE --title=$HOSTNAME --admin_user=admin --admin_email=admin@example.com --skip-email --allow-root
          fi
        service: cli

environments:
  master:
    cronjobs:
      - name: cronjob
        schedule: "H * * * *"
        command: wp cron event run --due-now --path=`/app/web/`
        service: cli
